sudo: false
services:
  - redis
language: ruby
rvm:
  - 2.6.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev
  - gem install bundler -v 1.13.6
script: bin/cibuild
notifications:
  email: false
