name: heroku/git_hub_integration/CI
on:
  push:
jobs:
  CI:
    runs-on: sfdc-hk-ubuntu-latest
    container:
      image: ruby:2.7.6
    services:
      redis:
        image: redis:latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |-
        gem install bundler
        sudo apt-get -qq update
        sudo apt-get install -y libsodium-dev
        bundle -v
    - name: Wait for Redis
      run: dockerize -wait tcp://localhost:6379 -timeout 1m
    - run: bin/setup
    - name: Run tests
      run: bin/cibuild
